#Change the hostname to match what you want yours to be, likely guacamole.yourdomain.com that is linked to your teams instance.
ingress:
  - hostname: ${hostname}
    service: ${service}
  - service: http_status:404
