version: "3"
services:
  guacamole:
    build: .
    #image: flcontainers/guacamole
    container_name: guacamole
    environment:
      TZ: 'UTC'
      EXTENSIONS: 'auth-totp,auth-header,auth-ldap,auth-quickconnect,history-recording-storage,vault'
    env_file:
      - .env
    volumes:
      - postgres:/config
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./filefs/startup2.sh
        target: /startup2.sh
    entrypoint: bash /startup2.sh
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local
